### ISSUE TITLE
Trying to get this assignment in before tuesday

### ISSUE THREAD

**Issue by JiffyBees** [JiffyBees/this-site-aint-no-sloth#1]
How to I get the lines in this assignment as well as the background pattern. I kind of stumped on how I would go about doing it. I know this isn't the final assignment but I want to get it finished.

@charlie-quinn

**Comment by charlie-quinn** [comment]
Hey Vanessa, I'm so sorry but I don't have ANY free time this week to troubleshoot past assignments. Your current grade is above 70%, I wouldn't worry too much about this one.

⚠️ Please close this issue when you have a minute.
